package com.ftn.sbnz.rules;

import com.ftn.sbnz.model.models.Call;
import com.ftn.sbnz.model.models.Patient;
import com.ftn.sbnz.model.assessment.PatientAssessment;
import com.ftn.sbnz.model.enums.EmergencyLevel;
import com.ftn.sbnz.model.enums.IncidentType;
import com.ftn.sbnz.model.enums.ConsciousnessLevel;
import com.ftn.sbnz.model.symptoms.InjuryHeadSymptoms;

// Pravilo: Povreda glave + nema svijesti + ne reaguje na nadražaje -> CRVENO
rule "Nivo2 - Head injury unconscious no reaction -> RED"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $assessment : PatientAssessment(callId == $id, consciousnessLevel == ConsciousnessLevel.UNCONSCIOUS_UNRESPONSIVE)
then
    modify($assessment){
        setPreliminaryLevel(EmergencyLevel.RED)
    };
    System.out.println("Nivo2 - Head injury: unconscious, no reaction -> RED " + $id);
end

// Pravilo: Povreda glave + nema svijesti + reaguje na nadražaje -> ŽUTO
rule "Nivo2 - Head injury unconscious with reaction -> YELLOW"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $assessment : PatientAssessment(callId == $id, consciousnessLevel == ConsciousnessLevel.UNCONSCIOUS_RESPONSIVE)
then
    modify($assessment){
        setPreliminaryLevel(EmergencyLevel.YELLOW)
    };
    System.out.println("Nivo2 - Head injury: unconscious, reacts -> YELLOW " + $id);
end

// Pravilo: Povreda glave + svijest prisutna -> ZELENO
rule "Nivo2 - Head injury conscious -> GREEN"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $assessment : PatientAssessment(callId == $id, consciousnessLevel == ConsciousnessLevel.CONSCIOUS)

then
    modify($assessment){
        setPreliminaryLevel(EmergencyLevel.GREEN)
    };
    System.out.println("Nivo2 - Head injury: conscious -> GREEN " + $id);
end

//NIVO 3

// Ako je preliminarno CRVENO ili ŽUTO i otvorena rana -> CRVENO (ostaje crveno ili postaje crveno)
rule "Nivo3 - Head injury RED/YELLOW + open wound -> RED"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $a : PatientAssessment(callId == $id, (preliminaryLevel == EmergencyLevel.RED || preliminaryLevel == EmergencyLevel.YELLOW), finalized == false)
    $symptoms : InjuryHeadSymptoms(callId == $id, openWound == true, vomiting == false)
then
    modify($a){
        setFinalLevel(EmergencyLevel.RED),
        setFinalized(true)
    };
    System.out.println("Nivo3 - Head injury: RED/YELLOW + open wound -> RED " + $id);
end

// Ako je preliminarno ZELENO i otvorena rana -> ŽUTO
rule "Nivo3 - Head injury GREEN + open wound -> YELLOW"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $a : PatientAssessment(callId == $id, preliminaryLevel == EmergencyLevel.GREEN, finalized == false)
    $symptoms : InjuryHeadSymptoms(callId == $id, openWound == true, vomiting == false)
then
    modify($a){
        setFinalLevel(EmergencyLevel.YELLOW),
        setFinalized(true)
    };
    System.out.println("Nivo3 - Head injury: GREEN + open wound -> YELLOW " + $id);
end

rule "Nivo3 - Head injury GREEN + vomiting -> YELLOW"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $a : PatientAssessment(callId == $id, preliminaryLevel == EmergencyLevel.GREEN, finalized == false)
    $symptoms : InjuryHeadSymptoms(callId == $id, vomiting == true, openWound == false)
then
    modify($a){
        setFinalLevel(EmergencyLevel.YELLOW),
        setFinalized(true)
    };
    System.out.println("Nivo3 - Head injury: GREEN + vomiting -> YELLOW " + $id);
end

rule "Nivo3 - Head injury GREEN + vomiting + open wound -> RED"
no-loop true
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $a : PatientAssessment(callId == $id, preliminaryLevel == EmergencyLevel.GREEN, finalized == false)
    $symptoms : InjuryHeadSymptoms(callId == $id, vomiting == true, openWound == true)
then
    modify($a){
        setFinalLevel(EmergencyLevel.YELLOW),
        setFinalized(true)
    };
    System.out.println("Nivo3 - Head injury: GREEN + vomiting + open wound -> RED " + $id);
end

rule "Nivo3 - Head injury default"
when
    $call : Call($id : id, incidentType == IncidentType.INJURY_HEAD)
    $a : PatientAssessment(callId == $id, preliminaryLevel != null, finalized == false)
    $symptoms : InjuryHeadSymptoms(callId == $id, vomiting == false, openWound == false)
then
    modify($a){
        setFinalLevel($a.getPreliminaryLevel()),
        setFinalized(true)
    };

    System.out.println("Nivo3 HEAD default " + $id);
end